services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netresearch\NrImageOptimize\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Netresearch\NrImageOptimize\Service\SystemRequirementsService:
    public: false

  Netresearch\NrImageOptimize\Controller\MaintenanceController:
    public: true
